name: varecof-env

channels:
    - conda-forge
    - auto-mech

dependencies:
    - cmake
    - gcc_linux-64
    - gxx_linux-64
    - blas
    - openblas # [linux]
    - conda-forge::mpich
    - auto-mech::slatec
