name: varecof-env

channels:
    # - conda-forge
    - auto-mech

dependencies:
    - cmake
    - gcc_linux-64
    - gxx_linux-64
    - blas
    - openblas # [linux]
    - mpich
    # - conda-forge::mpich doesn't give executables for some reason
    - auto-mech::slatec
