# cmd conda build . -c auto-mech
package:
    name: varecof
    version: "1.0.0"

source:
    path: .

requirements:
    build:
        - cmake
        - blas
        - openblas # [linux]
        - slatec
        - mpi
        - dl
    run:
        - cmake
        - blas
        - openblas # [linux]
        - slatec
        - mpi
        - dl
