# cmd conda build . -c auto-mech -c conda-forge
package:
    name: varecof
    version: "0.2.0"

source:
    path: .

requirements:
    build:
        - conda-forge::cmake=3.21.3
        - conda-forge::gcc_linux-64=11.2.0
        - conda-forge::gxx_linux-64=11.2.0
        - conda-forge::blas
        - conda-forge::openblas # [linux]
        - conda-forge::mpich
        # - conda-forge::mpich doesn't give executables for some reason
        - auto-mech::slatec
    run:
        - conda-forge::cmake=3.21.3
        - conda-forge::gcc_linux-64=11.2.0
        - conda-forge::gxx_linux-64=11.2.0
        - conda-forge::blas
        - conda-forge::openblas # [linux]
        - conda-forge::mpich
        # - conda-forge::mpich doesn't give executables for some reason
        - auto-mech::slatec
