# cmd conda build . -c auto-mech
package:
    name: varecof
    version: "0.1.0"

source:
    path: .

requirements:
    build:
        - cmake
        - gcc_linux-64
        - gxx_linux-64
        - blas
        - openblas # [linux]
        - mpi
        # - dl
        - auto-mech::slatec
    run:
        - cmake
        - gcc_linux-64
        - gxx_linux-64
        - blas
        - openblas # [linux]
        - mpi
        # - dl
        - auto-mech::slatec
